### ISSUE TITLE
ModuleNotFoundError: No module named 'fruit_feature'

### ISSUE THREAD

**Issue by Gayathri831** [animeesh/Image_processing#1]
why is this error getting to me?  and This fruit_feature is not defined, right? we have to install any package or else not needed.

**Comment by animeesh** [comment]
i am glad you have gone through my repo I will get back to you soon

**Comment by animeesh** [comment]
you need to put fruit_feature.py  in the same repo where you are working on.
thankyou.
if any new errors, do reply.

**Comment by Gayathri831** [comment]
Thank you for your response.

I'm still facing the same issue. This "fruit_feature import
extract_features" code is not working and I'm getting continuous errors.
even though I tried with your code, still the same errors happening.

**Comment by animeesh** [comment]
I would like connect to you so i can serve you better
7977656012 is my number or else connect to me in linkedin

**Comment by animeesh** [comment]
hi sorry for inconvenience,
actully this repo is just for the references for technique, there is no train folder or anything and the codes are not even cleaned. I would suggest referring to some other repo or else let me know what your agenda is to do.
